avatar: /assets/logo.jpg # ç½‘ç«™ Logo
background: # æ—¢æ˜¯åšå®¢çš„èƒŒæ™¯ï¼Œåˆæ˜¯æ–‡ç« é»˜è®¤å¤´å›¾
  path: /assets/backg.jpg
  width: 1440
  height: 960
favicon:
  href: /assets/logo.jpg # ç½‘ç«™å›¾æ ‡
  type: image/x-icon # å›¾æ ‡ç±»å‹ï¼Œå¯èƒ½çš„å€¼æœ‰(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # åŠŸèƒ½å¼€å…³ï¼Œå¯é€‰å€¼ï¼ˆtrue,falseï¼‰
  globalToc: true # å¼€å¯è¯¥åŠŸèƒ½ä¼šè‡ªåŠ¨å¼€å¯æ–‡ç«  TOCï¼ˆæ–‡ç« ç›®å½•ï¼‰ åŠŸèƒ½
  darkmode: false # æ˜¯å¦å¯ç”¨æš—è‰²ä¸»é¢˜ï¼Œå¯é€‰å€¼ï¼ˆtrue,falseï¼‰
  wordCount: true # æ˜¯å¦å¼€å¯æ–‡ç« å­—æ•°ç»Ÿè®¡ (true, false)

imageCDN: # å›¾ç‰‡ CDN åŠŸèƒ½
  enable: false # å¼€å¯è¯¥åŠŸèƒ½  
  origin: /../../images/ # å›¾ç‰‡åŸå§‹ç›®å½•
  to: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/ # å›¾ç‰‡ CDN åŸŸå
  
# é™„åŠ å›¾æ ‡åº“ ä½¿ç”¨è¯´æ˜ï¼šhttps://docs.nexmoe.com/config/icon
iconlib: # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

search: 
  type: engine # å¯é€‰engineï¼ˆç”¨æœç´¢å¼•æ“æœç´¢ï¼‰ã€swiftypeã€æˆ–localï¼ˆæœ¬åœ°æœç´¢ï¼‰
  url: https://cn.bing.com/search?q=site:sxrekord.com # æœç´¢å¼•æ“åœ°å€ï¼Œåœ¨typeä¸ºswiftypeæ—¶æ— æ•ˆ e.g:https://www.google.com/search?q={ä½ çš„åšå®¢é“¾æ¥}
  id: <swiftype-id> # swiftypeçš„idï¼Œè§å¯ç”¨æ•™ç¨‹ã€‚åœ¨typeä¸ºengineæ—¶æ— æ•ˆ

cdn: # è¿™é‡Œå¯ä»¥ä¿®æ”¹ç«™ç‚¹ä½¿ç”¨çš„åº“çš„CDN
  disqusjs: 
    css: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqusjs.min.css
    js: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqus.min.js
  gitalk:
    css: https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.css
    js: https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
  valine:
    js: https://cdn.jsdelivr.net/npm/valine

menu:
  å›åˆ°é¦–é¡µ: 
    - /
    - icon-home
#  æ–‡ç« å½’æ¡£:  # ä½¿ç”¨è¯´æ˜ï¼šhttps://docs.nexmoe.com/article/archive
#    - /archive.html
#    - icon-container
  å…³äºåšä¸»:
    - /about.html
    - icon-info-circle
  æˆ‘çš„æœ‹å‹: 
    - /PY.html # ä½¿ç”¨è¯´æ˜ï¼šhttps://docs.nexmoe.com/article/py
  æ¯æ—¥é€›é€›:
    - /dalao.html
    - icon-eye-fill
  æ–‡ç« å½’æ¡£:
    - /archives.html
    - icon-container

widgets:
- search
- hitokoto
- social
- category
- tagcloud
# - archive #settings: widgetAchive
# - recent_posts
# - link #settings: widgetLink

maxTagcloud: 0  # æ ‡ç­¾äº‘ç»„ä»¶æ˜¾ç¤ºçš„æ ‡ç­¾æ•°é‡ï¼Œ0 è¡¨ç¤ºä¸é™åˆ¶

social:
  å“”å“©å“”å“©:
    - https://space.bilibili.com/456872732
    - icon-bilibili
    - rgb(231, 106, 141)
    - rgba(231, 106, 141, .15)
  GitHub:
    - https://github.com/Crazyokd/
    - icon-github
    - rgb(25, 23, 23)
    - rgba(25, 23, 23, .15)
  è±†ç“£:
    - https://www.douban.com/people/232567446/
    - icon-douban-fill
    - rgb(51, 153, 51)
    - rgba(51, 51, 51, .15)
  Steam:
    - https://steamcommunity.com/id/crazyokd
    - icon-steam
    - rgb(0, 51, 139)
    - rgba(0, 51, 153, .15)
  Telegram:
    - https://telegram.me/crazyokd
    - icon-telegram
    - rgb(0, 191, 255)
    - rgba(0, 191, 255, .15)
  çŸ¥ä¹:
    - https://www.zhihu.com/people/jing-2-73-45
    - icon-zhihu
    - rgb(30, 144, 255)
    - rgba(30, 144, 255, .15)  
  RSS:
    - /atom.xml
    - icon-rss
    - rgb(235, 152, 0)
    - rgba(235, 152, 0, .15)  
  è…¾è®¯QQ:
    - https://wpa.qq.com/msgrd?v=3&uin=1324596506&site=qq&menu=yes
    - icon-QQ
    - rgb(2, 125, 250)
    - rgba(2, 125, 250, .15) 


# è‡ªå®šä¹‰æ ·å¼ï¼Œå¯ç”¨åå¯åœ¨ç«™ç‚¹çš„sourceæ–‡ä»¶å¤¹ä¸‹æ–°å»ºcustom.cssè‡ªå®šä¹‰ç«™ç‚¹æ ·å¼
customstyle: false  
color: # é…è‰²æ–¹æ¡ˆï¼Œä»firståˆ°seventhä¸ºä¼˜å…ˆçº§ä¸º1-7çš„é¢œè‰²ï¼Œé»˜è®¤ä¸ºå½©è™¹é…è‰²
  first: # åŒæ—¶ä½œä¸ºä¸»é¢˜è‰²
    r: 255 
    g: 78
    b: 106
  second:
    r: 255
    g: 118
    b: 30
  third:
    r: 255
    g: 185
    b: 0
  fourth:
    r: 51
    g: 213
    b: 122
  fifth:
    r: 0
    g: 219
    b: 255
  sixth:
    r: 26
    g: 152
    b: 255
  seventh:
    r: 144
    g: 144
    b: 255

# å‘æœç´¢å¼•æ“éªŒè¯ä½ å¯¹ç«™ç‚¹çš„æ‰€æœ‰æƒï¼Œç”¨äºå‘æœç´¢å¼•æ“æäº¤ sitemap å’Œç®¡ç†ç«™ç‚¹è¢«æœç´¢å¼•æ“æ”¶å½•çš„æƒ…å†µã€‚
site_verification: 
  google:
  baidu:

# ç»Ÿè®¡ç³»ç»Ÿï¼Œç›®å‰æ”¯æŒ Google analytics.js ç»Ÿè®¡ã€Google Tag Manager ç»Ÿè®¡ã€CNZZ ç»Ÿè®¡ã€è…¾è®¯ç»Ÿè®¡ã€51.Laç»Ÿè®¡ã€ç™¾åº¦ç»Ÿè®¡
analytics: 
  baidu_site_id: 62280469c0e16c563480bdb503ef4f1f

# è¯„è®ºæ¡†ï¼Œç›®å‰æ”¯æŒ gitalk,gitment,valine,disqus,disqusjs,changyan,livere,DiscussBot ä½¿ç”¨ false å¯ä»¥å…³é—­
comment: gitalk
gitalk:
  admin: Crazyokd # æ‹¥æœ‰å¯¹è¯¥repoè¿›è¡Œæ“ä½œçš„ GitHub username
  owner: Crazyokd # æŒæœ‰è¯¥ repo çš„ GitHub username
  repo: rekord-blog # å­˜æ”¾è¯„è®ºçš„ issue æ‰€åœ¨çš„ repo
  clientID: b640e2db71a95cb19b24 # GitHub Client ID
  clientSecret: f095962d7b7040d25063c4713b8dfe4c6441b78e # GitHub Client Secret
gitment:
  owner: Crazyokd # æŒæœ‰è¯¥ repo çš„ GitHub username
  repo: rekord-blog # å­˜æ”¾è¯„è®ºçš„ issue æ‰€åœ¨çš„ repo
  clientID: b640e2db71a95cb19b24 # GitHub Client ID
  clientSecret: f095962d7b7040d25063c4713b8dfe4c6441b78e # GitHub Client Secret

copyright: '<strong>ç‰ˆæƒå£°æ˜ï¼š</strong>æœ¬æ–‡é‡‡ç”¨ <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> åè®®è¿›è¡Œè®¸å¯'
copyTip: "è‘—ä½œæƒå½’ä½œè€…æ‰€æœ‰ã€‚\nå•†ä¸šè½¬è½½è¯·è”ç³»ä½œè€…è·å¾—æˆæƒï¼Œéå•†ä¸šè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚\næ¥æºï¼š%url" # è‡ªå®šä¹‰å¤åˆ¶ç‰ˆæƒæ–‡æ¡ˆ,ä½¿ç”¨ %url ä»£æ›¿å½“å‰é¡µé¢URL, ä¿®æ”¹ä¸ºfalseç¦ç”¨

# achive widget behavior
widgetAchive: #æ–‡ç« å½’æ¡£ç»„ä»¶
  archive_type: 'year' #æŒ‰æœˆå±•ç¤ºè¿˜æ˜¯æŒ‰å¹´å±•ç¤º
  show_count: true  #æ˜¯å¦å±•ç¤ºæ•°é‡

widgetLink: #é“¾æ¥ç»„ä»¶
  - title: <title>
    img : <img_path>
    link : <url>
  - title: <title>
    img : <img_path>
    link : <url>

widgetHitokoto: # ä¸€è¨€ç»„ä»¶
  loading_placeholder: 'ğŸš€ è·å–ä¸­...' # æ­£åœ¨ä¸€è¨€æ—¶çš„å ä½ç¬¦
  loading_error_placeholder: 'ğŸ è·å–å¤±è´¥...' # åŠ è½½ä¸€è¨€å¤±è´¥æ—¶çš„å ä½ç¬¦
  category: # ä¸€è¨€å¥å­ç±»å‹ï¼ˆå¯é€‰ï¼‰ï¼Œä¸é…ç½®çš„è¯éšæœºè·å–ï¼Œè¯¦è§ https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0

# è‡ªå®šä¹‰ä¾§è¾¹æ å°¾éƒ¨å†…å®¹
sidebar: '<br><a target="_blank" href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral"></a>'

# hexo generator feed
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: false
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: 
  autodiscovery: true
  template: